webapi3/upload/urls.py
from django.conf.urls import url
from upload import views

urlpatterns = [
    url(r'^$', views.form, name = 'form'),
]

webapi3/webapi3/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('upload.urls', namespace='upload')),
]

webapi3/upload/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

# Create your models here.
from django.db import models
from datetime import datetime


class FileNameModel(models.Model):
    file_name = models.CharField(max_length=50)
    upload_time = models.DateTimeField(default=datetime.now)

webapi3/upload/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from __future__ import print_function

from django.shortcuts import render
from django.http import HttpResponse
from upload.models import FileNameModel
import os
import threading
from tasks import voice_rgb

UPLOADE_DIR = os.path.dirname(os.path.abspath(__file__)) + '/static/files/'
TARGET_FILE = ''


def form(request):
    if request.method != 'POST':
        return render(request, 'upload/form.html')

    apikey = request.POST['api-key']
    upload_file = request.FILES['file']
    path = os.path.join(UPLOADE_DIR, upload_file.name)
    destination = open(path, 'wb')

    for chunk in upload_file.chunks():
        destination.write(chunk)

    # 結果をDBに保存
    insert_data = FileNameModel(file_name=upload_file.name)
    insert_data.save()

    # ファイルアップロード後、Empathにファイルを送信し、結果を受け取る
    print("upload done.")
    t = threading.Thread(target=voice_rgb, args=(path, apikey, ))
    t.start()

    return HttpResponse(status=200)

webapi3/upload/templates/upload/base.html
<!DOCTYPE html>
<html lang="ja">
    <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <meta name="viewport" content="content">
        <title>ファイルアップローダ</title>
    </head>
    <body>
        {% block content %}
            {{ content }}
        {% endblock %}
    </body>
</html>

webapi3/upload/templates/upload/complete.html
{% extends "upload/base.html" %}

{% block title %}アップロード完了{% endblock title %}
{% block content %}
    <div align="center">
        <h1 align="center">アップロード完了</h1>
        <a href="{% url 'upload:form' %}"><button>戻る</button></a>
    </div>
{% endblock content %}

webapi3/upload/templates/upload/form.html
{% extends "upload/base.html" %}

{% block title %}アップローダサンプル{% endblock title %}
{% block content %}
    <form method="POST" enctype="multipart/form-data">
        api-key<input type="text" size="46" name="api-key"><br>
        <input type="file" name="file">
        <input type="submit" value="アップロード">
    </form>
{% endblock content %}